platform :ios, '8.0'
#use_frameworks!个别需要用到它，比如reactiveCocoa

target 'demo_UINavigationController' do
  pod 'AFNetworking', '~> 2.6'
  pod 'MBProgressHUD', '~>0.9.2'
  pod 'MJRefresh', '~> 3.1.0'
  pod 'Masonry', '~> 0.6.4'
end
